name: flutter_back_locator
description: "package backgprundf location android and ios"
version: 0.0.1
homepage: https://github.com/msilvabo/flutter_back_locator

environment:
  sdk: ^3.5.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: yukams.app.background_locator_2
        pluginClass: BackgroundLocatorPlugin
      ios:
        pluginClass: BackgroundLocatorPlugin
